### ISSUE TITLE
Clarify support for this extension

### ISSUE THREAD

**Issue by xurizaemon** [alok0590/CiviCRM-Membership-Period-Extension#1]
Please advise whether this extension is supported or a research project (etc).

See compucorp/uk.co.compucorp.membership#2 for discussion.

**Comment by alok0590** [comment]
@xurizaemon 
This extension is a research project and not supported. I've updated READ ME to clarify the same.

**Comment by agilewarealok** [comment]
@xurizaemon 
This extension is now production ready and can be used on CiviCRM installations. Have updated readme for the same.
